### ISSUE TITLE
Not sure if this is an issue...

### ISSUE THREAD

**Issue by dc8948** [cpear/BlazorComponentBus#3]
Will this work on the client-side in a WASM or PWA App? Looking for a way for a central service to communicate to components so they can self-update when a change happens. 

Apologize if this is the wrong place to ask questions like this.

**Comment by cpear** [comment]
I have not tried to see if this will work with WebAssembly at this point or Blazor Client. Right now its just Blazor server side. It sounds like what you are looking to do is push a notification from the server side that would alert all of the components in the UI that an event has happened or a change in data has occurred or something to that effect.

If that is the case then it seems feasible that you could put together a solution using Blazor Server since its really sitting on top of SignalR.

There is probably a much better way but you could essentially create a Razor Component that has no display elements, and its job would be to do some kind of processing or polling of an API and send message out via BlazorComponentBus to notify the other components that something has changed.

**Comment by lonix1** [comment]
@Psypher9 Thanks for that useful feedback! I wrote about that [concern here](https://github.com/cpear/BlazorComponentBus/issues/10). Are you still in dev mode, or do you use it in a production app?

**Comment by Psypher9** [comment]
@lonix1 yes we are using this in several production applications.
